### ISSUE TITLE
Apple Silicon (arm64) support for the Proffie tools package

### ISSUE THREAD

**Issue by n4phth4** [profezzorn/arduino-proffieboard#14]
The "arm-none-eabi-gcc" toolset with version "9-2020-q2-update" per the current "package_proffieboard_index.json" does not offer a native build of the tools package for Apple ARM64 arch (M1, M2, etc).  We are 2+ years since public release of Apple ARM64 arch and humbly ask for a native build of this toolset.

Arduino IDE recently released 2.0.3 with a native Apple ARM64.  [_Granted, various tools within its bundled arduino-cli -- like serial-discovery and mdns-discovery -- are actually also only built for x86_64 arch on macOS with no ARM64 (separate issue to be taken up with them).  This can be mitigated by building those Golang projects from source on macOS readily and easily though._]. It would be great if the board toolsets would support this arch as well.

I got to the point of compilation of ProffieOS only to have it fail due to bad CPU type of the executables.

`Compilation error: fork/exec /Users/myUser/Library/Arduino15/packages/proffieboard/tools/arm-none-eabi-gcc/9-2020-q2-update/bin/arm-none-eabi-g++: bad CPU type in executable`

**Comment by profezzorn** [comment]
I thought M1 macs were able to run x86 binaries just fine, albeit a bit slower?

**Comment by profezzorn** [comment]
Next time I upgrade the arduino-proffieboard compiler, I will certainly look to see if an mac-arm64 toolchain is available.
Last time I did it, it wasn't available, which is why there isn't one available now.
(I didn't compile the toolchain myself, I just downloaded it from the arm-gcc website.)

Since an easy workaround exists, I'm not going to spend a lot of time on this particular problem. If you don't want to install rosetta that is your choice, but for now that is the recommended way to make the arduino-proffieboard plugin work on M1/M2 macs.

If you compile your own toolchain, and it works properly, and it's the same version of GCC as the rest of arduino-proffieboard uses, I'd be happy to add that to the arduino-proffieboard plugin so that other people can use it.
 I can't really provide a lot of advice on how to do that though, since I didn't actually do it myself for any of the other platforms.

**Comment by profezzorn** [comment]
All the offical arm-gcc toolchains builds and sources can be found here:
https://developer.arm.com/downloads/-/gnu-rm

I'm guessing they will also have some information about how to build your own, but I have not looked for that.
I suspect that "jenkins" refers to a continuous integration system.

**Comment by profezzorn** [comment]
The only assembler code in GCC is the parts that *generate* code, not *run* code, so I think it's just a matter of making it compile. There may be minor issues, but in a broader sense it should just work. I think the instructions reflect what has been tested, not what is possible.
